name: Scrape de datos más recientes

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '42 */3 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Get data
      run: |-
        wget -t 3 -O estructura_autoridades_apn.csv 'https://mapadelestado.jefatura.gob.ar/includes/estructura_csv.php?r=0'
    - name: Commit & push if changed
      run: |-
        date=$(date)
        git config user.name "Automatic"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        git commit -m "Cambios"|| exit 0
        git push
