name: Scrape de datos más recientes

on:
  push:
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Get data
      run: |-
        wget -t 3 -O estructura_autoridades_apn.csv --user-agent="Mozilla/5.0 (X11; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0'" 'https://mapadelestado.jefatura.gob.ar/includes/estructura_csv.php?r=0'
    - name: Commit & push if changed
      run: |-
        date=$(date)
        git config user.name "Automatic"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        git commit -m "Cambios"|| exit 0
        git push
