name: Scrape de datos más recientes

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '42 */3 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Get data
      run: |-
        curl 'https://mapadelestado.jefatura.gob.ar/includes/estructura_csv.php?r=0' \
        curl 'https://mapadelestado.jefatura.gob.ar/includes/estructura_csv.php?r=0' \
        -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0' \
        -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8' \
        -H 'Accept-Language: en,en-US;q=0.8,en-GB;q=0.5,es-ES;q=0.3' \
        -H 'DNT: 1' \
        -H 'Alt-Used: mapadelestado.jefatura.gob.ar' \
        -H 'Connection: keep-alive' \
        -H 'Referer: https://datos.gob.ar/' \
        -H 'Upgrade-Insecure-Requests: 1' \
        -H 'Sec-Fetch-Dest: document' \
        -H 'Sec-Fetch-Mode: navigate' \
        -H 'Sec-Fetch-Site: cross-site' \
        -H 'Sec-Fetch-User: ?1' \
        -H 'Sec-GPC: 1'
        -H 'Connection: keep-alive' \
        -H 'Pragma: no-cache' \
        -H 'Cache-Control: no-cache' \
        --compressed > estructura_autoridades_apn.csv
    - name: Commit & push if changed
      run: |-
        date=$(date)
        git config user.name "Automatic"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        git commit -m "Cambios"|| exit 0
        git push
